let products=[],cart=JSON.parse(localStorage.getItem('ca_cart')||'[]'),customProduct=null,customImage='';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=n=>Number(n||0).toFixed(2).replace('.',',');
function save(){localStorage.setItem('ca_cart',JSON.stringify(cart));renderCart()}
function renderCart(){let qty=cart.reduce((a,b)=>a+b.qty,0),total=cart.reduce((a,b)=>a+b.price*b.qty,0);$('#count').textContent=qty;$('#cartTotal').textContent=$('#drawerTotal').textContent=money(total);$('#cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="ci"><b>${esc(x.name)}</b><br><small>${esc(x.personalization||'Fără text personalizat')}</small><div class="qty"><button onclick="qty(${i},-1)">−</button> ${x.qty} <button onclick="qty(${i},1)">+</button> · ${money(x.price*x.qty)} lei <button onclick="removeItem(${i})">Șterge</button></div></div>`).join(''):'<p>Coșul este gol.</p>'}
function qty(i,d){cart[i].qty=Math.max(1,cart[i].qty+d);save()} function removeItem(i){cart.splice(i,1);save()} function toggleCart(){$('#cart').classList.toggle('hidden')}
async function load(){products=await fetch('api/products.php').then(r=>r.json());let cats=[...new Set(products.map(p=>p.category).filter(Boolean))];$('#category').innerHTML+=[...cats].map(c=>`<option>${esc(c)}</option>`).join('');renderProducts()}
function renderProducts(){let q=$('#search').value.toLowerCase(),cat=$('#category').value,a=products.filter(p=>(!q||(p.name+' '+p.description).toLowerCase().includes(q))&&(!cat||p.category===cat));if($('#sort').value==='priceAsc')a.sort((x,y)=>x.price-y.price);if($('#sort').value==='priceDesc')a.sort((x,y)=>y.price-x.price);$('#products').innerHTML=a.map(p=>`<article class="card"><img src="${esc(p.image)}" alt="${esc(p.name)}"><small>${esc(p.category)}</small><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p>${p.old_price?`<span class="old">${money(p.old_price)} lei</span> `:''}<b class="price">${money(p.price)} lei</b><p>Stoc: ${p.stock}</p><div class="actions"><button onclick="quickAdd(${p.id})">Adaugă</button><button class="gold" onclick="customize(${p.id})">Personalizează</button></div></article>`).join('')||'<p>Nu am găsit produse.</p>'}
function quickAdd(id){let p=products.find(x=>+x.id===+id);if(!p||+p.stock<1)return alert('Produs indisponibil.');let x=cart.find(x=>+x.id===+id&&!x.personalization&&!x.personalization_image);if(x)x.qty++;else cart.push({id:p.id,name:p.name,price:+p.price,qty:1,personalization:'',personalization_image:''});save()}
function customize(id){customProduct=products.find(x=>+x.id===+id);customImage='';$('#customName').textContent=customProduct.name;$('#personalText').value='';$('#previewText').textContent='';$('#preview').style.backgroundImage=`url("${customProduct.image}")`;$('#uploadedPreview').classList.add('hidden');$('#personalImage').value='';$('#customizer').classList.remove('hidden')}
function closeCustomizer(){$('#customizer').classList.add('hidden')}
$('#personalText').addEventListener('input',e=>$('#previewText').textContent=e.target.value);
$('#personalImage').addEventListener('change',e=>{let f=e.target.files[0];if(!f)return;if(f.size>1500000){alert('Imaginea este prea mare. Folosește maximum 1,5 MB în această versiune.');e.target.value='';return}let r=new FileReader;r.onload=()=>{customImage=r.result;$('#uploadedPreview').src=customImage;$('#uploadedPreview').classList.remove('hidden')};r.readAsDataURL(f)});
function addCustomized(){if(!customProduct)return;cart.push({id:customProduct.id,name:customProduct.name,price:+customProduct.price,qty:1,personalization:$('#personalText').value.trim(),personalization_image:customImage});save();closeCustomizer();toggleCart()}
async function sendOrder(){if(!cart.length){$('#msg').textContent='Coșul este gol.';return}let body={name:$('#name').value,email:$('#email').value,phone:$('#phone').value,address:$('#address').value,details:$('#details').value,items:cart};let r=await fetch('api/order.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json().catch(()=>({ok:false,message:'Eroare server.'}));$('#msg').textContent=j.ok?`Comanda #${j.order_id} a fost înregistrată. Total: ${money(j.total)} lei.`:(j.message||'Eroare la comandă.');if(j.ok){cart=[];save()}}
['#search','#category','#sort'].forEach(s=>$(s).addEventListener(s==='#search'?'input':'change',renderProducts));save();load();
