<!doctype html>
<html lang="ro"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CreativArt — Articole personalizate</title><link rel="stylesheet" href="assets/style.css"></head>
<body>
<div class="top">Livrare în toată România • Cadouri personalizate • Comenzi online</div>
<header><a class="logo" href="./">Creativ<span>Art</span></a><nav><a href="#produse">Produse</a><a href="#categorii">Categorii</a><a href="#despre">Despre noi</a><a href="account.php">Contul meu</a><a href="admin/">Admin</a></nav></header>
<section class="hero"><div><span class="eyebrow">CADOURI CU SUFLET</span><h1>Transformă amintirile în <em>cadouri speciale</em></h1><p>Căni, perne, tablouri și alte articole personalizate cu fotografia și mesajul tău.</p><a class="btn" href="#produse">Vezi produsele</a></div></section>
<section class="benefits"><div>✦<b>Personalizare</b><small>Fotografie + mesaj</small></div><div>♡<b>Cadouri speciale</b><small>Pentru orice ocazie</small></div><div>▣<b>Livrare națională</b><small>Oriunde în România</small></div><div>✓<b>Comandă simplă</b><small>Direct de pe site</small></div></section>
<main>
<section id="categorii"><div class="sectionTitle"><span>DESCOPERĂ</span><h2>Categorii populare</h2></div><div class="cats"><button data-cat="Căni">☕<b>Căni</b></button><button data-cat="Perne">▧<b>Perne</b></button><button data-cat="Tablouri">▣<b>Tablouri</b></button><button data-cat="">✦<b>Toate</b></button></div></section>
<section id="produse"><div class="sectionTitle"><span>CREATIVART</span><h2>Produse personalizate</h2></div>
<div class="filters"><input id="search" placeholder="Caută un produs..."><select id="category"><option value="">Toate categoriile</option></select><select id="sort"><option value="new">Cele mai noi</option><option value="priceAsc">Preț crescător</option><option value="priceDesc">Preț descrescător</option></select></div>
<div id="products" class="products"><div class="loading">Se încarcă produsele…</div></div></section>
<section id="despre" class="about"><div><span>DESPRE CREATIVART</span><h2>Un cadou creat special pentru cineva drag</h2><p>Alege produsul, adaugă mesajul și fotografia ta, iar noi pregătim personalizarea. Previzualizarea te ajută să vezi ideea înainte de comandă.</p></div><div class="quote">„Momentele frumoase merită păstrate.”</div></section>
<section class="checkout"><h2>Finalizează comanda</h2><p>Completează datele după ce ai adăugat produsele în coș.</p><div class="formgrid"><input id="name" placeholder="Nume și prenume"><input id="email" type="email" placeholder="Email (opțional)"><input id="phone" placeholder="Telefon"><input id="address" placeholder="Adresă de livrare"></div><textarea id="details" placeholder="Detalii suplimentare"></textarea><button class="btn" onclick="sendOrder()">Trimite comanda</button><p id="msg"></p></section>
</main>
<footer><div class="logo">Creativ<span>Art</span></div><p>Articole personalizate pentru momente speciale.</p><small>© 2026 CreativArt</small></footer>
<button class="cartBtn" onclick="toggleCart()">🛒 <span id="count">0</span> · <span id="cartTotal">0,00</span> lei</button>
<aside id="cart" class="drawer hidden"><button class="x" onclick="toggleCart()">×</button><h2>Coșul tău</h2><div id="cartItems"></div><h3>Total: <span id="drawerTotal">0,00</span> lei</h3><a href="#produse" onclick="toggleCart()" class="btn">Continuă cumpărăturile</a></aside>
<section id="customizer" class="modal hidden"><div class="custombox"><button class="x" onclick="closeCustomizer()">×</button><div class="customgrid"><div id="preview" class="preview"><img id="uploadedPreview" class="uploaded hidden"><div id="previewText"></div></div><div><span>PERSONALIZARE</span><h2 id="customName"></h2><label>Mesajul tău</label><textarea id="personalText" placeholder="Ex: La mulți ani!"></textarea><label>Fotografia ta</label><input id="personalImage" type="file" accept="image/*"><p class="muted">Previzualizarea este orientativă.</p><button class="btn" onclick="addCustomized()">Adaugă în coș</button></div></div></div></section>
<script src="assets/app.js"></script></body></html>